# Copyright (C) 2019 Simen Thorsrud
# @author Simen Thorsrud <simen.thorsrud@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    Siment\MaintenanceBundle\Command\GreetCommand:
        tags:
            - { name: 'console.command' }