# Copyright (C) 2019 Simen Thorsrud
# @author Simen Thorsrud <simen.thorsrud@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    Siment\MaintenanceBundle\Command\MaintenanceEnableCommand:
        tags:
            - { name: 'console.command' }
        arguments:
            $name: ~
            $mode: '@Siment\MaintenanceBundle\ModeManager\MaintenanceModeManagerInterface'
    Siment\MaintenanceBundle\Command\MaintenanceDisableCommand:
        tags:
            - { name: 'console.command' }
        arguments:
            $name: ~
            $mode: '@Siment\MaintenanceBundle\ModeManager\MaintenanceModeManagerInterface'
    Siment\MaintenanceBundle\Command\MaintenanceStatusCommand:
        tags:
            - { name: 'console.command' }
        arguments:
            $name: ~
            $mode: '@Siment\MaintenanceBundle\ModeManager\MaintenanceModeManagerInterface'
    Siment\MaintenanceBundle\EventListener\RequestListener:
        arguments:
            $t: '@twig'
            $mode: '@Siment\MaintenanceBundle\ModeManager\MaintenanceModeManagerInterface'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 1000000 }
    Siment\MaintenanceBundle\ModeManager\MaintenanceModeManager:
        arguments:
            $cache: '@cache.app'
    Siment\MaintenanceBundle\ModeManager\MaintenanceModeManagerInterface: '@Siment\MaintenanceBundle\ModeManager\MaintenanceModeManager'